cadence:
  url: "https://apps.lrs.lt/sip/p2b.ad_seimo_kadencijos"
spring:
  application:
    name: "Pocket Seimas"
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop # Options: update, create, create-drop (best for dev)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: "logs/app.log"
  level:
    root: INFO
    com.pocketseimas: DEBUG

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ssl_pass
    key-store-type: PKCS12
    key-alias: ssl_alias
    enabled: true
  http:
    port: 8080
  error:
    whitelabel:
      enabled: false